"""add_composite_indexes_unique_constraint_and_trace_events

Revision ID: 4474f21970f1
Revises: a7e3f2d01b84
Create Date: 2026-05-18 15:48:49.148128

"""
from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4474f21970f1'
down_revision: str | None = 'a7e3f2d01b84'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_definitions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_agent_definition_id_version', ['agent_id', 'version'])

    with op.batch_alter_table('agent_deployments', schema=None) as batch_op:
        batch_op.create_index('ix_deployment_agent_channel', ['agent_id', 'channel'], unique=False)

    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trace_events_json', sa.JSON(), nullable=True))
        batch_op.create_index('ix_run_agent_status', ['agent_id', 'status'], unique=False)
        batch_op.create_index('ix_run_session', ['session_id', 'agent_id'], unique=False)

    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_session_agent_user', ['agent_id', 'user_id'], unique=False)

    with op.batch_alter_table('deployment_audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_agent_channel', ['agent_id', 'channel'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployment_audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_agent_channel')

    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_session_agent_user')

    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_run_session')
        batch_op.drop_index('ix_run_agent_status')
        batch_op.drop_column('trace_events_json')

    with op.batch_alter_table('agent_deployments', schema=None) as batch_op:
        batch_op.drop_index('ix_deployment_agent_channel')

    with op.batch_alter_table('agent_definitions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_agent_definition_id_version', type_='unique')

    # ### end Alembic commands ###
