"""initial tables

Revision ID: 4dcf2bc95572
Revises: 
Create Date: 2026-05-15 22:17:30.398293

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4dcf2bc95572'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definitions',
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('manifest_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_definitions_agent_id'), 'agent_definitions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_definitions_status'), 'agent_definitions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_definitions_tenant_id'), 'agent_definitions', ['tenant_id'], unique=False)
    op.create_table('agent_deployments',
    sa.Column('deployment_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('traffic_percent', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_deployments_agent_id'), 'agent_deployments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_deployments_channel'), 'agent_deployments', ['channel'], unique=False)
    op.create_index(op.f('ix_agent_deployments_deployment_id'), 'agent_deployments', ['deployment_id'], unique=True)
    op.create_index(op.f('ix_agent_deployments_tenant_id'), 'agent_deployments', ['tenant_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('agent_version', sa.String(length=64), nullable=False),
    sa.Column('route_reason', sa.String(length=128), nullable=True),
    sa.Column('runtime_backend', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tool_calls_json', sa.JSON(), nullable=True),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_id'), 'agent_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_request_id'), 'agent_runs', ['request_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_run_id'), 'agent_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_agent_runs_session_id'), 'agent_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_tenant_id'), 'agent_runs', ['tenant_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('location_id', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('history_json', sa.JSON(), nullable=True),
    sa.Column('state_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_agent_id'), 'agent_sessions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_session_id'), 'agent_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_agent_sessions_tenant_id'), 'agent_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_table('deployment_audit_events',
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('traffic_percent', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('previous_version', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('artifact_id', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_audit_events_agent_id'), 'deployment_audit_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_deployment_audit_events_channel'), 'deployment_audit_events', ['channel'], unique=False)
    op.create_index(op.f('ix_deployment_audit_events_event_type'), 'deployment_audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_deployment_audit_events_tenant_id'), 'deployment_audit_events', ['tenant_id'], unique=False)
    op.create_table('eval_runs',
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('agent_version', sa.String(length=64), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=False),
    sa.Column('required_pass_rate', sa.Float(), nullable=False),
    sa.Column('gate_passed', sa.Boolean(), nullable=False),
    sa.Column('results_json', sa.JSON(), nullable=True),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_agent_id'), 'eval_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_eval_runs_tenant_id'), 'eval_runs', ['tenant_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('delivery_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_delivery_id'), 'webhook_deliveries', ['delivery_id'], unique=True)
    op.create_index(op.f('ix_webhook_deliveries_tenant_id'), 'webhook_deliveries', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_deliveries_tenant_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_delivery_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_eval_runs_tenant_id'), table_name='eval_runs')
    op.drop_index(op.f('ix_eval_runs_agent_id'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_deployment_audit_events_tenant_id'), table_name='deployment_audit_events')
    op.drop_index(op.f('ix_deployment_audit_events_event_type'), table_name='deployment_audit_events')
    op.drop_index(op.f('ix_deployment_audit_events_channel'), table_name='deployment_audit_events')
    op.drop_index(op.f('ix_deployment_audit_events_agent_id'), table_name='deployment_audit_events')
    op.drop_table('deployment_audit_events')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_tenant_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_session_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_agent_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_agent_runs_tenant_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_session_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_request_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_agent_deployments_tenant_id'), table_name='agent_deployments')
    op.drop_index(op.f('ix_agent_deployments_deployment_id'), table_name='agent_deployments')
    op.drop_index(op.f('ix_agent_deployments_channel'), table_name='agent_deployments')
    op.drop_index(op.f('ix_agent_deployments_agent_id'), table_name='agent_deployments')
    op.drop_table('agent_deployments')
    op.drop_index(op.f('ix_agent_definitions_tenant_id'), table_name='agent_definitions')
    op.drop_index(op.f('ix_agent_definitions_status'), table_name='agent_definitions')
    op.drop_index(op.f('ix_agent_definitions_agent_id'), table_name='agent_definitions')
    op.drop_table('agent_definitions')
    # ### end Alembic commands ###
