"""add_dead_letter_queue

Revision ID: dbbf495e5dfc
Revises: 4474f21970f1
Create Date: 2026-05-19 03:17:30.157140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbbf495e5dfc'
down_revision: Union[str, None] = '4474f21970f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter_entries',
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dead_letter_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dead_letter_entries_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dead_letter_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dead_letter_entries_tenant_id'))

    op.drop_table('dead_letter_entries')
    # ### end Alembic commands ###
